"""Enforce the supported Chroma deployment: local Rust, caller-supplied vectors.

This does not patch the Python Chroma server. That server and its RBAC providers
are outside the application deployment and must not be exposed separately.
"""

from pathlib import Path

import chromadb
from chromadb.api.rust import RustBindingsAPI
from chromadb.config import Settings

REVIEWED_CHROMA_VERSION = "1.5.9"
LOCAL_BACKEND = "chromadb.api.rust.RustBindingsAPI"


def create_local_chroma_client(persist_directory: str | None = None):
    if chromadb.__version__ != REVIEWED_CHROMA_VERSION:
        raise RuntimeError("ChromaDB version changed: review the local security controls before use")
    # Explicit values override environment variables that could otherwise select
    # the Python segment backend or an HTTP client/server authorization provider.
    settings = Settings(
        chroma_api_impl=LOCAL_BACKEND,
        anonymized_telemetry=False,
        chroma_server_host=None,
        chroma_server_authn_provider=None,
        chroma_server_authz_provider=None,
        chroma_client_auth_provider=None,
    )
    if persist_directory:
        Path(persist_directory).mkdir(parents=True, exist_ok=True)
        client = chromadb.PersistentClient(path=persist_directory, settings=settings)
    else:
        client = chromadb.EphemeralClient(settings=settings)
    if type(client._server) is not RustBindingsAPI:
        raise RuntimeError("Only the local Rust Chroma backend is supported")
    return client


def get_local_collection(client, name: str):
    # Never use the default EF: all vectors are generated by Node 2. None also
    # avoids supplying an EF; the facade below also blocks schema EF fallback.
    collection = client.get_collection(name=name, embedding_function=None)
    config = collection._model.configuration_json.get("embedding_function")
    # Old application collections may contain the harmless default EF config.
    # Other configs are rejected; no automatic model migration/loading occurs.
    if config is not None and config not in ({"name": "default", "config": {}},
                                           {"type": "known", "name": "default", "config": {}}):
        raise ValueError("Collection has an unsupported persisted embedding function")
    return VectorOnlyCollection(collection)


def create_local_collection(client, name: str, metadata: dict):
    return VectorOnlyCollection(client.create_collection(
        name=name, metadata=metadata, embedding_function=None))


class VectorOnlyCollection:
    """Expose only operations with explicit vectors, never text/URI embedding.

Chroma 1.5.9 may fall back to a schema EF even when the provided EF is None.
This boundary prevents that fallback rather than relying on None alone.
"""
    def __init__(self, collection):
        self._collection = collection

    def count(self):
        return self._collection.count()

    @property
    def metadata(self):
        return self._collection.metadata

    def add(self, *, ids, documents, embeddings, metadatas):
        if embeddings is None:
            raise ValueError("Explicit embeddings are required")
        return self._collection.add(ids=ids, documents=documents, embeddings=embeddings, metadatas=metadatas)

    def upsert(self, *, ids, documents, embeddings, metadatas):
        if embeddings is None:
            raise ValueError("Explicit embeddings are required")
        return self._collection.upsert(ids=ids, documents=documents, embeddings=embeddings, metadatas=metadatas)

    def query(self, *, query_embeddings=None, n_results=3, **kwargs):
        if query_embeddings is None or kwargs:
            raise ValueError("Only explicit query embeddings are supported")
        return self._collection.query(query_embeddings=query_embeddings, n_results=n_results)
